Repository HongikComputerClub/gift-front, pull requests merged in 2025-02, with the labels that each got.

#9 Feature/#4
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/Buttons/NextButton.jsx
  src/components/Buttons/SelectionButton.jsx
  src/components/Buttons/ThemeNextButton.jsx
  src/components/Buttons/ThemeSelectButton.jsx
  src/components/Description/Description.jsx
  src/components/Description/ThemeDescription.jsx
  src/components/common/Button.jsx
  src/components/common/Footer.css
  src/components/common/Footer.jsx
  src/components/common/Header.css
  src/components/contexts/UserContext.jsx
  src/components/icons/female_icon.svg
  src/components/icons/male_icon.svg
  src/components/icons/ribbon_left.svg
  src/components/icons/ribbon_right.svg
  src/components/onboarding/SlideImage.jsx
  src/components/onboarding/StartButton.jsx
  src/pages/GiftThemeSelection.jsx
  src/pages/Onboarding.jsx
  src/pages/Questionnaire.jsx
  src/styles/GiftThemeSelection/GiftThemeSelection.css
  src/styles/buttons/NextButton.css
  src/styles/buttons/SelectionButton.css
  src/styles/buttons/ThemeButton.css
  src/styles/buttons/ThemeSelectButton.css
  src/styles/description/Description.css
  src/styles/description/ThemeDescription.css
  src/styles/onboarding/SlideImage.css
  src/styles/onboarding/StartButton.css
Labels: :sparkles: feature

#11 New Feature/#4
  src/assets/icons/female_icon.svg
  src/assets/icons/male_icon.svg
  src/assets/icons/ribbon_left.svg
  src/assets/icons/ribbon_right.svg
  src/components/Buttons/SelectionButton.jsx
  src/components/Buttons/ThemeNextButton.jsx
  src/components/Buttons/ThemeSelectButton.jsx
  src/components/Description/ThemeDescription.jsx
  src/components/common/Footer.css
  src/components/common/Footer.jsx
  src/pages/GiftThemeSelection.jsx
  src/pages/KakaoTalkAgree.jsx
  src/pages/Onboarding.jsx
  src/pages/Questionnaire.jsx
  src/styles/buttons/NextButton.css
  src/styles/buttons/SelectionButton.css
  src/styles/buttons/ThemeButton.css
  src/styles/buttons/ThemeSelectButton.css
  src/styles/description/Description.css
  src/styles/description/ThemeDescription.css
  src/styles/onboarding/SlideImage.css
  src/styles/onboarding/StartButton.css
Labels: :sparkles: feature

#15 Feature/#10
  package-lock.json
  package.json
  public/Montserrat-VariableFont_wght.ttf
  public/data/data.json
  src/assets/img_kakao/notCheck.svg
  src/assets/img_result/character1.svg
  src/assets/img_result/character2.svg
  src/assets/img_result/ground.svg
  src/components/common/Button.jsx
  src/components/kakao/Agree.jsx
  src/components/kakao/AgreePopup.jsx
  src/components/kakao/FileUpload.jsx
  src/components/kakao/WriteName.jsx
  src/components/result/Card.jsx
  src/components/result/Inventory.jsx
  src/components/result/Loading.jsx
  src/components/result/Ment2.jsx
  src/components/result/MoveShopping.jsx
  src/index.css
  src/styles/kakao/Agree.css
  src/styles/kakao/AgreePopup.css
  src/styles/kakao/FileUpload.css
  src/styles/kakao/Ment.css
  src/styles/kakao/WriteName.css
  src/styles/result/Inventory.css
  src/styles/result/Loading.css
  src/styles/result/MoveShopping.css
Labels: :sparkles: feature, :hammer: chore

#21 CI/CD 설정
  .github/workflows/front-build.yml
Labels: CI
